plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - 'examples/**/*'
    - 'tmp/**/*'
    - 'spec/support/**/*'
    - 'api_examples/support/**/*'
    - 'vendor/bundle/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Lint/IneffectiveAccessModifier:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'bin/'
    - 'spec/**/*'
    - 'uploadcare-ruby.gemspec'
    - 'api_examples/support/**/*.rb'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
    - 'api_examples/support/**/*.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'api_examples/support/**/*.rb'

Metrics/AbcSize:
  Max: 28
  Exclude:
    - 'api_examples/support/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'api_examples/support/**/*.rb'

Metrics/PerceivedComplexity:
  Max: 11
  Exclude:
    - 'api_examples/support/**/*.rb'

Metrics/ParameterLists:
  Max: 8
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/OptionalBooleanParameter:
  AllowedMethods: ['create']

Style/FrozenStringLiteralComment:
  Exclude:
    - 'api_examples/**/*'

Style/ArgumentsForwarding:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/IteratedExpectation:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/ClassCheck:
  Enabled: false
