AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Lint/IneffectiveAccessModifier:
  Enabled: false

Style/HashTransformKeys:
  Exclude:
    - 'lib/uploadcare/entity/decorator/paginator.rb'
    - 'lib/uploadcare/client/conversion/video_conversion_client.rb'
    - 'lib/uploadcare/entity/file.rb'

Metrics/BlockLength:
  Exclude:
    - 'bin/'
    - 'spec/**/*'
    - 'uploadcare-ruby.gemspec'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  AllowedMethods: ['create']
