AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Lint/IneffectiveAccessModifier:
  Enabled: false

Style/HashTransformKeys:
  Exclude:
    - 'lib/uploadcare/entity/decorator/paginator.rb'
    - 'lib/uploadcare/client/conversion/video_conversion_client.rb'
    - 'lib/uploadcare/entity/file.rb'

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'uploadcare-ruby.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'bin/'
    - 'spec/**/*'
    - 'uploadcare-ruby.gemspec'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  AllowedMethods: ['create']
