AllCops:
  TargetRubyVersion: 2.7

Metrics/LineLength:
  Max: 120

IneffectiveAccessModifier:
  Enabled: false

Style/HashTransformKeys:
  Exclude:
    - 'lib/uploadcare/entity/decorator/paginator.rb'
    - 'lib/uploadcare/client/conversion/video_conversion_client.rb'

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'uploadcare-ruby.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'bin/'
    - 'spec/**/*'
    - 'uploadcare-ruby.gemspec'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  AllowedMethods: ['create']
