AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Lint/IneffectiveAccessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'bin/'
    - 'spec/**/*'
    - 'uploadcare-ruby.gemspec'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  AllowedMethods: ['create']

Style/FrozenStringLiteralComment:
  Exclude:
    - 'api_examples/**/*'
